### ISSUE TITLE
Cant confiscate items

### ISSUE THREAD

**Issue by XvenDeR** [GMA950/esx_inventoryhud_shops_2.0#1]
So faced this issue when I can't confiscate any items if I have enough space for it. If inventory is full you can confiscate items... Very weird...

**Comment by GMA950** [comment]
check your essential mode version, and i think that is a problem of esx_policejob and this resource.

check this tutorial for fix issues with esx_policejob

https://github.com/Nertigel/esx_inventoryhud/blob/master/WIKI.md

**Comment by XvenDeR** [comment]
Latest version of essentialmode and es_extended also did that fix for esx_policejob... Well I will keep looking further what could it be then.

**Comment by TMarcccci** [comment]
Hey XcenDer can you send me the Enhanced HUD? Cause im using ESX

**Comment by XvenDeR** [comment]
> Hey XcenDer can you send me the Enhanced HUD? Cause im using ESX

that hud sux
